import { StyleSheet, FlatList } from 'react-native';
import { colors, semanticColors } from "src/app/styles/colors";


export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: semanticColors.mainbackground },
    box: { width: 24, height: 24 },
    box2: { marginBottom: 11 },
    button: {
      alignItems: "center",
      backgroundColor: colors.batteryChargedBlue + "4D",
      borderRadius: 10,
      paddingVertical: 16,
      marginBottom: 22,
      marginHorizontal: 28,
    },
    buttonDisabled: {
      alignItems: "center",
      backgroundColor: colors.batteryChargedBlue + "4D",
      borderRadius: 10,
      paddingVertical: 16,
      marginBottom: 22,
      marginHorizontal: 28,
    },
    buttonEnabled: {
      alignItems: "center",
      backgroundColor: colors.batteryChargedBlue,
      borderRadius: 10,
      paddingVertical: 16,
      marginBottom: 22,
      marginHorizontal: 28,
    },
    buttonRow: {
      flexDirection: "row",
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderRadius: 6,
      borderWidth: 1,
      paddingVertical: 11,
      paddingHorizontal: 13,
      marginBottom: 20,
      marginHorizontal: 19,
    },
    image: { width: 24, height: 24 },
    image2: { width: 22, height: 22 },
    input: {
      color: colors.lightSilver,
      fontSize: 14,
      fontWeight: "bold",
      marginBottom: 20,
      marginHorizontal: 19,
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderRadius: 6,
      borderWidth: 1,
      paddingVertical: 11,
      paddingLeft: 12,
      paddingRight: 24,
    },
    input2: {
      color: colors.charcoal,
      fontSize: 14,
      fontWeight: "bold",
      marginBottom: 137,
      marginHorizontal: 19,
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderRadius: 6,
      borderWidth: 1,
      paddingVertical: 11,
      paddingLeft: 12,
      paddingRight: 24,
    },
    inputContent: {
      color: colors.charcoal,
      fontSize: 14,
      fontWeight: "bold",
      marginBottom: 20,
      marginHorizontal: 19,
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderRadius: 6,
      borderWidth: 1,
      paddingVertical: 11,
      paddingLeft: 12,
      paddingRight: 24,
      minHeight: 100,
      textAlignVertical: "top",
    },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: semanticColors.mainbackground,
      paddingVertical: 16,
      paddingHorizontal: 17,
      marginBottom: 20,
    },
    scrollView: { flex: 1, backgroundColor: semanticColors.mainbackground },
    text: { color: semanticColors.text, fontSize: 16, fontWeight: "bold" },
    text2: { color: semanticColors.text, fontSize: 12, fontWeight: "bold", marginBottom: 12, marginLeft: 19 },
    text3: { color: colors.lightSilver, fontSize: 14, fontWeight: "bold", flex: 1 },
    text4: { color: semanticColors.text, fontSize: 12, fontWeight: "bold", marginBottom: 5, marginLeft: 19 },
    text5: { color: colors.lightSilver, fontSize: 14, fontWeight: "bold", marginLeft: 12 },
    text6: { color: colors.white, fontSize: 16, fontWeight: "bold" },
    view: {
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderRadius: 6,
      borderWidth: 1,
      paddingTop: 11,
      paddingBottom: 20,
      marginBottom: 20,
      marginHorizontal: 19,
    },
    dropdown: {
      backgroundColor: semanticColors.mainbackground,
      borderColor: colors.lightSilver,
      borderWidth: 1,
      borderRadius: 6,
      marginHorizontal: 19,
      marginBottom: 10,
      overflow: "hidden",
    },
    dropdownItem: {
      paddingVertical: 12,
      paddingHorizontal: 16,
    },
    dropdownText: {
      color: semanticColors.text,
      fontSize: 16,
    },
    formContainer: {
      padding: 16,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    messageInput: {
      height: 120,
    },
    submitButton: {
      backgroundColor: colors.primary,
      borderRadius: 8,
      padding: 16,
      alignItems: 'center',
      marginTop: 16,
    },
    submitButtonText: {
      color: colors.white,
      fontSize: 16,
      fontWeight: '600',
    },
    typeSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.white,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    typeText: {
      fontSize: 16,
      color: colors.text,
    },
    placeholderText: {
      color: colors.textSecondary,
    },
    arrowIcon: {
      width: 20,
      height: 20,
      tintColor: colors.textSecondary,
    },
    typeList: {
      backgroundColor: colors.white,
      borderRadius: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    typeItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    typeItemText: {
      fontSize: 16,
      color: colors.text,
    },
  });